import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
})

const clashGrotesk = localFont({
  variable: "--font-clash-grotesk",
  src: [
    {
      path: "/fonts/clash_grotesk/ClashGrotesk-Extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "/fonts/clash_grotesk/ClashGrotesk-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "/fonts/clash_grotesk/ClashGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/clash_grotesk/ClashGrotesk-Medium.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "/fonts/clash_grotesk/ClashGrotesk-Semibold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "/fonts/clash_grotesk/ClashGrotesk-Bold.woff2",
      weight: "800",
      style: "normal",
    },
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${spaceGrotesk.variable} ${clashGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
